# Generated by Django 4.1 on 2022-11-24 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menu_type',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.CharField(max_length=15),
        ),
    ]
