# Generated by Django 4.1 on 2022-11-25 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_menu_menu_type_alter_menu_name_alter_menu_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('uploaded', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='mango',
            name='ripe',
        ),
        migrations.AlterField(
            model_name='menu',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
