# Generated by Django 4.1 on 2022-11-30 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_cart_name_cart_product_alter_cart_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cart',
            table=None,
        ),
    ]
