# Generated by Django 4.1 on 2022-12-01 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_cart_owner_remove_cart_product_cart_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='uploaded',
        ),
        migrations.AddField(
            model_name='product',
            name='menu_type',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ManyToManyField(related_name='products', to='api.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=15),
        ),
    ]
