# Generated by Django 4.1 on 2022-11-26 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_cart_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='name',
        ),
        migrations.AddField(
            model_name='menu',
            name='image',
            field=models.ImageField(default=1, upload_to='files/covers'),
            preserve_default=False,
        ),
    ]
