# Generated by Django 4.1 on 2022-11-26 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_cart_name_menu_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='image',
        ),
    ]
